name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0

    - name: Set up Python
      uses: actions/setup-python@v6.0.0
      with: 
        python-version: 3.13
    
    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit_report.json # -ll=severity level medium or high,  -ii=confident level medium or high

    - name: Upload Artifact
      uses: actions/upload-artifact@v5.0.0 
      if: always() #even the previouse one is failed, run this
      with: 
        name: bandit-findings
        path: bandit_report.json
  
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      with: 
        docker-version: '20.10.7'
    
    - name: Build Docker Image
      run: docker build -f Dockerfile -t myapp:latest .

    - name: Docker Scout Scan
      run: |
        curl -fSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        sh install-scout.sh

        echo ${{secrets.REPO_PWO}} | docker login -u ${{secrets.REPO_USER}} --password-stdin
        
        docker scout quickview
        docker scout cves
